### ISSUE TITLE
训练数据包含在百度网盘里？

### ISSUE THREAD

**Issue by sirlancer** [xiaomaxiao/keras_ocr#10]
你好，我读了下你的CRNN的代码，发现训练数据有从json格式中读出，但我在你给的百度云连接中并没有找到，而且我发现你这只有训练的代码好像并没有测试的代码，你的准确率怎么来的？是先训练集上？

**Comment by zhdy008** [comment]
这块代码自己改掉吧，用 train.txt 和 test.txt 替代
