### ISSUE TITLE
建议用HDF5重新写一下训练和测试数据

### ISSUE THREAD

**Issue by colinlin1982** [xiaomaxiao/keras_ocr#12]
我用一块1080ti的显卡在做训练，发现显卡占用率只有6%左右。
因为图片太小了，磁盘IO效率很低，瓶颈在磁盘IO上。

建议将图片文件处理成HDF5，既不需要解压缩，载入和训练速度也更快。

**Comment by xiaomaxiao** [comment]
谢谢建议。
