### ISSUE TITLE
关于字符集的问题

### ISSUE THREAD

**Issue by yien450** [xiaomaxiao/keras_ocr#14]
你好，我使用百度网盘中的char_std_5990.txt后，开头的blank也会被输入到字符集中，nclass=5995而不是5990，这个问题如何解决？谢谢。而且5988也不是最后的有效字符

**Comment by xiaomaxiao** [comment]
https://github.com/xiaomaxiao/keras_ocr/blob/master/densent_ocr/char_std_5990.txt
