### ISSUE TITLE
可以分享一下你训练好的18.9MB大小的模型文件么？

### ISSUE THREAD

**Issue by JohnTian** [xiaomaxiao/keras_ocr#16]
@xiaomaxiao 你好！
我看到你在README.md文件中提到 `densent+ctc	8ms	 0.982	18.9MB`
冒昧的问一下，18.9MB的模型文件是`E:\deeplearn\OCR\Sample\model\weights-densent-09.hdf5` 么？
如果是的话，可以分享一下么？
万分感谢！

**Comment by yohacai** [comment]
他这个模型是抄袭的，不用找他要了

**Comment by JohnTian** [comment]
@yohacai 好的。
