### ISSUE TITLE
楼主能请问Json.load（)中的jsonpath 是您数据集中的train.txt文件还是其他什么的文件

### ISSUE THREAD

**Issue by pixixiaonaogou** [xiaomaxiao/keras_ocr#3]

**Comment by pixixiaonaogou** [comment]
嗯嗯，谢谢楼主，但是从你给的百度网盘下载的数据集，不能完全解压，可以分享一下其他的数据集吗？或者楼主有权重分享吗

**Comment by xiaomaxiao** [comment]
这个数据集是 caffe_ocr作者的， 我当时也解压了很久 而且还缺了一部分，360解压似乎不行，ZIP 好点。
权重的话 暂时不能
